// Joins src/characters/*.js into src/js/characters.gen.js (gitignored), the one
// script tag index.html keeps for them, so adding a character edits no shared file.
//
//   node scripts/characters.mjs           rebuild the bundle
//   node scripts/characters.mjs --list    one line per character, to see the cast at a glance
//   node scripts/characters.mjs --json    the same cast as database rows, on stdout
//
// Each file carries a character's row (handle, joined, lastCommit, github, look,
// voice) and its look code (dress). --json prints exactly the row half, in the
// column names a backend would use, so seeding or checking a table is one command;
// dress has no column and stays in the repository.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { runInNewContext } from "node:vm";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

export const writeCharacters = () => {
  const dir = join(root, "src", "characters");
  const files = readdirSync(dir).filter((f) => f.endsWith(".js")).sort();
  const body = files.map((f) => `// ---- characters/${f} ----\n${readFileSync(join(dir, f), "utf8").trim().replace(/\r\n/g, "\n")}`).join("\n\n");
  writeFileSync(join(root, "src", "js", "characters.gen.js"), `// Generated by scripts/characters.mjs from src/characters/; do not edit.\n${body}\n`);
  return files.length;
};

// The registry as the page builds it, under a minimal window shim.
export const readCharacters = () => {
  writeCharacters();
  const context = { window: {}, URLSearchParams, location: { search: "" } };
  for (const name of ["math", "scene", "models", "characters", "characters.gen"]) {
    runInNewContext(readFileSync(join(root, "src", "js", `${name}.js`), "utf8"), context);
  }
  return context.window.BL.characters.all();
};

const iso = (seconds) => new Date(seconds * 1e3).toISOString();
export const characterRows = () => readCharacters().map((c) => ({
  handle: c.handle,
  github_login: c.github || c.handle,
  display: c.display || null,
  joined_at: iso(c.joined),
  last_commit_at: iso(c.lastCommit),
  look: c.look || {},
  voice: c.voice || null,
  has_look_code: !!c.dress
}));

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const arg = process.argv[2];
  if (arg === "--json") console.log(JSON.stringify(characterRows(), null, 1));
  else if (arg === "--list") {
    const rows = characterRows();
    for (const row of rows) {
      const look = Object.keys(row.look).join(" ") || "hashed";
      console.log(`${row.handle.padEnd(16)} joined ${row.joined_at.slice(0, 10)}  ${row.has_look_code ? "code" : "    "}  ${row.voice ? "voice" : "     "}  ${look}`);
    }
    console.log(`${rows.length} characters`);
  } else console.log(`characters: ${writeCharacters()} files`);
}
