// Regenerates src/js/jumbotron-data.js: node scripts/jumbotron-data.mjs <path-or-url-to-stats.json>.
// Build/refresh time only - the page stays network-free.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = process.argv[2];
if (!source) {
  console.error("usage: node scripts/jumbotron-data.mjs <path-or-url-to-stats.json>");
  process.exit(2);
}

const text = /^https?:/.test(source)
  ? await (await fetch(source)).text()
  : readFileSync(source, "utf8");
const stats = JSON.parse(text);
if (stats?.meta?.schema_version !== 1) {
  console.error(`unexpected schema_version: ${stats?.meta?.schema_version}`);
  process.exit(1);
}

// Ship public handles and activity only, never profile names or metadata.
const counts = ({ commits, prs, reviews, comments }) => ({
  commits, prs, reviews,
  comments: { issue: comments.issue, review: comments.review, commit: comments.commit, all: comments.all }
});
const snapshot = {
  meta: { generated_at: stats.meta.generated_at, repo: stats.meta.repo, schema_version: stats.meta.schema_version },
  totals: { contributors: stats.totals.contributors, ...counts(stats.totals) },
  leaderboards: Object.fromEntries(["commits", "prs", "reviews", "comments"].map((kind) => [kind,
    stats.leaderboards[kind].map(({ login, count }) => ({ login, count }))
  ])),
  contributors: stats.contributors.map((c) => ({
    login: c.login,
    last_seen_at: c.last_seen_at,
    counts: counts(c.counts),
    weekly: c.weekly.map(({ week, commits, prs, reviews, comments }) => ({ week, commits, prs, reviews, comments }))
  }))
};

const out = join(root, "src", "js", "jumbotron-data.js");
writeFileSync(
  out,
  `// Generated by scripts/jumbotron-data.mjs from an oogatron /v1/stats snapshot.
// Do not edit by hand.
(() => {
  "use strict";
  const BL = window.BL = window.BL || {};
  BL.jumbotronData = ${JSON.stringify(snapshot)};
})();
`,
);
console.log(`wrote ${out} (${stats.contributors.length} contributors, generated_at ${stats.meta.generated_at})`);
